### ISSUE TITLE
Can't use prompt-confirm

### ISSUE THREAD

**Issue by nschoe** [enquirer/prompt-confirm#1]
Hi,
Sorry it's me again.  
I don't know if this is linked or not (because I had not used `prompt-confirm` before), but since I pulled the latest version of `enquirer`, to solve enquirer/enquirer#6, I cannot use the `prompt-confirm`.

For information (maybe this is useful) I have `git pull`ed the `enquirer` project, then I `cd`ed to my workspace and did `npm install /path/to/enquirer/clone`, it installed and I could use `enquirer`.
Now I am trying to use `prompt-confirm` and this fails, here is a minimal snippet that fails on me:

``` Javascript
'use strict';

const Enquirer = require('enquirer')
const inspect = require ('util').inspect


function query (i) {
    let enquirer = new Enquirer ()

    enquirer.register ('confirm', require ('enquirer-prompt-confirm'))

    enquirer.question ('QuestionA', 'Question A (' + i + ')?', {
        type: 'confirm'
    })
    enquirer.question ('QuestionB', 'Question B (' + i + ')?', {
        type: 'confirme',
    })

    enquirer.ask()
    .then (answers => {
        console.log ('Answers #' + i)
        console.log (inspect (answers))
        console.log ('--')

        if (i > 0) {
            console.log ('Asking for argument ' + i + ' now...')
            query (i-1)
        }
    })
    .catch( err => {
        console.error ('Err: ' + err)
    })
}

query (3)
```

As you noticed, I have used the same template to chain `prompt-confirm` commands, but it fails at the first: it asks me the first question, but then when I answer it fails. Here is the console session:

``` Bash
? Question A (3)? Yesreadline.js:982
            throw err;
            ^

TypeError: this.ui.write is not a function
    at Confirm.onSubmit (/home/nschoe/workspace/xxx/node_modules/enquirer-prompt-confirm/index.js:71:11)
    at UI.on (/home/nschoe/workspace/xxx/node_modules/component-emitter/index.js:65:8)
    at UI.Emitter.emit (/home/nschoe/workspace/xxx/node_modules/component-emitter/index.js:133:20)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:239:10)
    at Interface._line (readline.js:585:8)
    at Interface._ttyWrite (readline.js:862:14)
    at ReadStream.onkeypress (readline.js:126:10)
    at emitTwo (events.js:111:20)
    at ReadStream.emit (events.js:191:7)
    at emitKeys (internal/readline.js:389:14)
    at next (native)
    at ReadStream.onData (readline.js:972:36)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
```

This is weird, so might it be a problem induced by the fix on `enquirer`? Or is it a cache or dependency error on my side?

**Comment by jonschlinkert** [comment]
> Or is it a cache or dependency error on my side?

I might be either, but it's easiest to test the latter first. can you try deleting `node_modules` and reinstalling?

**Comment by doowb** [comment]
>  enquirer.register ('confirm', require ('enquirer-prompt-confirm'))

`enquirer-prompt-confirm` has been deprecated and renamed to `prompt-confirm`.

> type: 'confirme',

Misspelling of `confirm`

After using `prompt-confirm` and correcting the typo it's working for me.

**Comment by jonschlinkert** [comment]
> After using prompt-confirm and correcting the typo it's working for me.

same, I didn't notice the typo at first

**Comment by nschoe** [comment]
Hi,
OMG I'm so sorry, for the `confirme` vs. `confirm` mistake!

As for the fact that `enquirer-prompt-confirm` has been deprecated and renamed to `prompt-confirm`, could you make it appear on the README page, like you did for [enquirer-prompt-radio](https://www.npmjs.com/package/enquirer-prompt-radio) here it's plainly clear that the package is deprecated and renamed, but it's not for `enquirer-prompt-confirm`.

I have fixed my mistake and used the new package, my test case works ok now. I haven't tried chaining the calls, but I don't see any reason why it would not work.

Thanks again for your work and reactivity guys! And sorry for the typo :/

(Please consider editing the README page for the deprecated package!)
