### ISSUE TITLE
Cannot send sigterm signal after confirm

### ISSUE THREAD

**Issue by mcorbe** [enquirer/prompt-confirm#13]
Sadly, I didn't find a workaround and moved to: https://www.npmjs.com/package/prompts

I need to be able to kill scripts at any point of time send a sigterm with ctrl+c, following the doc: https://nodejs.org/api/process.html#process_signal_events
```
process.on('SIGINT', () => {
  process.exit(0);
});
```

Once this is resolved, I could use this package again ;). Happy to help.

**Comment by doowb** [comment]
@mcorbe this project has been archived: See [this comment](https://github.com/enquirer/prompt-confirm/issues/9#issuecomment-437127186) for more information.

Try using the [Confirm prompt](https://github.com/enquirer/enquirer#confirm-prompt) in Enquirer directly. If you run into any issues with that, please feel free to open an issue there.

**Comment by tswaters** [comment]
I've just encountered this myself...  not being able to ctrl-C is a no bueno for me.  So, just to confirm -- is this package is deprecated in favour of enquirer?  

It might be good to archive in github / deprecate in npm?  Right now, aside from no recent commits, there is no indication in the readme that this project has been archived.
