### ISSUE TITLE
How to set default value to false?

### ISSUE THREAD

**Issue by nschoe** [enquirer/prompt-confirm#2]
Hi,

I'm trying to use `prompt-confirm` to ask the user a question, but the prompts defaults to `(Y/n)` and when simply pressing `<Enter>` the answer is set to `true`.

By using `{default: false}` (hinted by [this](https://github.com/enquirer/prompt-confirm/blob/master/index.js#L20)) I managed to make the prompt defaults to `(y/N)`, but even so, just pressing `<Enter>` without writing anything sets the answer to `false`.

Basic example below:

``` Javascript
'use strict';

const inspect  = require ('util').inspect
const Enquirer = require ('enquirer')

let enquirer = new Enquirer ()
enquirer.register ('confirm', require ('prompt-confirm'))

enquirer.question ('agree', 'Do you agree?', {
    type: 'confirm',
    default: false
})

enquirer.ask()
.then( answer => {
    console.log ('Answer: ' + inspect (answer, {colors: true}))
})
```

And the console session that goes with it:

``` Bash
? Do you agree? (y/N) #Pressing <Enter>

? Do you agree? true
Answer: { agree: true }
```

(Note that I displayed the the question twice simply to show that the prompt indeeds switches to `(y/N)`, but there are no display problem, it doesn't actually get repeated).

As you see, simply pressing enter sets the answer to `false`.

I tried setting `defaultValue: false` as well in the parameters, but it doesn't work.

**Comment by nschoe** [comment]
After looking at the code, I think the fix should happen [here](https://github.com/enquirer/prompt-confirm/blob/master/index.js#L59). It check if the input is a string, if yes it returns `isTrue(input)` otherwise it defaults to `this.question.default`. (**EDIT** ~~By the way, shouldn't it rather be `this.question.defaultValue`?~~ I tried it and no, actually, `this.question.defaultValue` is `undefined`)

With my test  code above, I have tested answer a number, and **now** it sets the answer to `false`. When I answer a string that begins with a space (**or only spaces**) then the answer is set to `false`.
But that is independent of the `default` that I gave. So I suppose it's `isTrue()` that returns false.

Anyway, I think the fix should not be too hard ^^

**Comment by nschoe** [comment]
Okay so I have tracked down the bug:

It's [at this line (I believe)](https://github.com/enquirer/prompt-confirm/blob/master/index.js#L59).

When you simply press `<Enter>` without giving any answer, the `isString()` function will return `''` (empty string), by the way, I don't understand why `isString()` is not simply `return typeof val === 'string'`, but anyway, we are lucky here, because `''` is interpreter as `false`.

So in `!!(isString(input) ? isTrue(input) : this.question.default);`, the condition is not respected, so what is returned is `this.question.default`, which has value `y/N`

Then the first `!` turns `y/N` into `false`, since a non-empty string is considered `true`.  
Then the second `!` turns this `false` into `true`.

So when we simply press `<Enter>`, we always get `true` in return :/

**Comment by jonschlinkert** [comment]
Do you want to do a pr?

**Comment by nschoe** [comment]
Yep, here I've just done it.  
Just check my question about `this.defaultValue` vs. `this.question.defaultValue`.
