### ISSUE TITLE
published packages should not have a package-lock

### ISSUE THREAD

**Issue by stevenvachon** [enquirer/prompt-confirm#4]
Devs and users end up with different versions

**Comment by jonschlinkert** [comment]
Agreed, even though NPM tells you to commit them. I started adding package-lock.json to `.gitignore`

**Comment by stevenvachon** [comment]
I use them for apps, but not libraries.

**Comment by jonschlinkert** [comment]
In either case, `package-lock.json` is poorly executed. But honestly, I've had [worse issues](https://github.com/yarnpkg/yarn/issues/3288) from yarn, so I'm a bit frustrated with the package manager situation in node atm

**Comment by jonschlinkert** [comment]
done
