### ISSUE TITLE
Remove [from view] when completed?

### ISSUE THREAD

**Issue by stevenvachon** [enquirer/prompt-confirm#5]
Would be nice for single confirmations such as "Are you sure?" that don't need to remain in the log.

**Comment by jonschlinkert** [comment]
I think this can be accomplished in the callback. You might be able to do something like `process.stdout.write('\r')`, but we'd probably need to move up a line if there is a linefeed there, I'll need to check

**Comment by jonschlinkert** [comment]
Here is an example for how to do this in implementations:

```js
var utils = require('readline-utils');
var Prompt = require('prompt-confirm');
var prompt = new Prompt({
  name: 'chocolate',
  message: 'Like chocolate?'
});

prompt.run()
  .then(logAnswer)
  .then(function() {
    return prompt.run();
  })
  .then(logAnswer);

function logAnswer(answer) {
  console.log(answer);
  return new Promise(function(resolve) {
    setTimeout(function() {
      // remove 3 lines (console.log adds a line)
      utils.clearLine(prompt.rl, 3);
      resolve();
    }, 1000);
  });
}
```

Closing since this is an implementation question, but I'd be happy to continue discussing.
