### ISSUE TITLE
Option to remove color and prefixed "?"

### ISSUE THREAD

**Issue by stevenvachon** [enquirer/prompt-confirm#6]
Would be nice for single confirmations

**Comment by jonschlinkert** [comment]
You should be able to do this currently. See the [examples in prompt-base](https://github.com/enquirer/prompt-base/blob/master/examples/ask.prefix.js). If something doesn't work there please let me know. 

fwiw I have a bunch of docs to push up (and a site) as soon as I have some time. A lot of this stuff will be explained there. and the experience and customizability will be really nice once the state/context stuff is done. You'll be able to easily change the appearance in different positions, based on status/state.

**Comment by stevenvachon** [comment]
Cool, thanks. I created an issue there for the prefix. How would we remove color from the answer and bold from the message?

**Comment by jonschlinkert** [comment]
try doing something like this:

```js
var prompt = new Prompt([...]);

prompt.renderMessage = function() {
  // customize `this.prefix` and `this.message` and return the message string
};
```

I believe that should work. let me know if you have any issues

**Comment by jonschlinkert** [comment]
@stevenvachon were you able to get this working?

**Comment by stevenvachon** [comment]
It worked just fine. Thank you.
