### ISSUE TITLE
Can't define default without name

### ISSUE THREAD

**Issue by stevenvachon** [enquirer/prompt-confirm#7]
```js
new Prompt({ message:"Are you Sure?", default:false }).run()
```
```
TypeError: expected name to be a non-empty string
    at new Question (/project/node_modules/prompt-question/index.js:61:11)
    at Confirm.Prompt (/project/node_modules/prompt-base/index.js:50:16)
    at new Confirm (/project/node_modules/prompt-confirm/index.js:14:10)
    at promiseTry.then (/project/scripts/dropdb.js:27:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

I don't even know what `name` is for and I shouldn't have to define it.

**Comment by jonschlinkert** [comment]
> I don't even know what name is for and I shouldn't have to define it.

What key should be used for setting an object of answers? We can remove support for returning an object of answers if that doesn't make sense either.

**Comment by stevenvachon** [comment]
Hmm, well I haven't yet tried the [enquirer](https://npmjs.com/enquirer) library, but will shortly. For my current use case, I have no use for an answer object as I only have one prompt.

**Comment by jonschlinkert** [comment]
> For my current use case, I have no use for an answer object as I only have one prompt.

I've thought about removing the need to have a name, but we'd still need to enforce it in enquirer. Even though you don't use enquirer it seems like it would make the experience inconsistent. just my 2c

**Comment by stevenvachon** [comment]
How about auto-generated values ("answer1", etc) by default?

**Comment by jonschlinkert** [comment]
> How about auto-generated values ("answer1", etc) by default?

Honestly, I think we should just go with your initial gut reaction and remove the requirement for `name`. If that was your perception, then I'll assume you're not the only one that will have that reaction. I'm fine with it
