### ISSUE TITLE
terminal default kill signal (ctrl+c) is being blocked

### ISSUE THREAD

**Issue by ngmariusz** [enquirer/prompt-confirm#9]
not only during prompt but also after up until process.kill()

---
vscode 1.23 terminal
ubuntu 16.04

**Comment by jonschlinkert** [comment]
thanks for reporting

**Comment by jonschlinkert** [comment]
I'm going to be pushing up a big refactor to the prompts in the next day or two. It should fix this issue and others.

**Comment by rudza** [comment]
Any progress on this?

**Comment by jonschlinkert** [comment]
Closing as this repository is being archived in lieu of [Enquirer 2.0](https://github.com/enquirer/enquirer). Please direct all questions, issues and feature requests to that repository.
